spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/crm
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  thymeleaf:
    suffix: .html


